import type { GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import getLayoutData from '../data/layout'
import Layout from '../components/layout'
import { HeaderProps } from '../components/header'
import { FooterProps } from '../components/footer'
import getHomePageData from '../data/home'
import {
  HeroUnit,
  HeroContent,
  HeroContentProps
} from '../components/hero-unit'

interface HomePageProps {
  header: HeaderProps
  footer: FooterProps
  heroImg: {
    media_details: {
      sizes: {
        full: {
          source_url: string
        }
      }
    }
  }
  page: {
    acf: HeroContentProps
  }
}

export default function Home(props: HomePageProps) {
  return (
    <Layout {...props}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroUnit imgSrc={props.heroImg.media_details.sizes.full.source_url}>
        <HeroContent
          content={props.page.acf.content}
          buttons={props.page.acf.buttons}
        />
      </HeroUnit>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  const layoutData = await getLayoutData()
  const pageData = await getHomePageData()
  return {
    props: {
      ...layoutData,
      ...pageData
    }
  }
}
