import type { GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import getLayoutData from '../data/layout'
import Layout from '../components/layout'
import { HeaderProps } from '../components/header'
import { FooterProps } from '../components/footer'

interface HomePageProps {
  header: HeaderProps
  footer: FooterProps
}

export default function Home(props: HomePageProps) {
  return (
    <Layout {...props}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  const layoutData = await getLayoutData()
  return {
    props: {
      ...layoutData
    }
  }
}
