import Head from 'next/head'
import {
  HeroContent,
  HeroContentProps,
  HeroUnit
} from '../components/hero-unit'
import Layout from '../components/layout'
import styled from 'styled-components'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import ContactForm from '../components/forms/contact'
import NewsletterForm from '../components/forms/newsletter'
import Request3dForm from '../components/forms/request-3d'
import { PageProps } from '../pages/[slug]'
import { WordPressPage } from '../data/types'

interface FormPage extends WordPressPage {
  template: 'page_form.php'
  acf: HeroContentProps & {
    form: 'newsletter' | 'request-3d' | 'contact'
  }
}
export interface FormPageProps extends PageProps {
  page: FormPage
}

export default function FormPage(props: FormPageProps) {
  return (
    <Layout {...props}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroUnit imgSrc={props.heroImg.media_details.sizes.full.source_url}>
        <HeroContent
          content={props.page.acf.content}
          buttons={props.page.acf.buttons}
        />
      </HeroUnit>
      <Main>
        <Row>
          <Col xs={12}>
            <Content>
              {props.page.acf.form ? (
                props.page.acf.form === 'newsletter' ? (
                  <NewsletterForm />
                ) : (
                  <Request3dForm />
                )
              ) : (
                <ContactForm />
              )}
            </Content>
          </Col>
        </Row>
      </Main>
    </Layout>
  )
}

const Main = styled(Container)`
  padding: 45px 15px;
`

const Content = styled.div`
  color: ${({ theme }) => theme.body};
  margin: 0 auto;
  max-width: 960px;
  padding: 45px 15px;

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    color: ${({ theme }) => theme.primary};
  }
`
