import Head from 'next/head'
import {
  HeroContent,
  HeroContentProps,
  HeroUnit
} from '../components/hero-unit'
import Layout from '../components/layout'
import styled from 'styled-components'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { PageProps } from '../pages/[slug]'
import Accordion, {
  AccordionContent,
  AccordionTitle
} from '../components/accordion'
import { SeriesPostType } from '../data/types'
import ModelInstallationFiles from '../components/model-installation-files'

export interface TypicalInstallationsPageProps extends PageProps {
  page: {
    template: 'page_typical-installations.php'
    content: {
      rendered: string
    }
    acf: HeroContentProps
  }
  filterSeries: SeriesPostType[]
  separatorSeries: SeriesPostType[]
}

export default function TypicalInstallationsPage(
  props: TypicalInstallationsPageProps
) {
  return (
    <Layout {...props}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroUnit imgSrc={props.heroImg.media_details.sizes.full.source_url}>
        <HeroContent
          content={props.page.acf.content}
          buttons={props.page.acf.buttons}
        />
      </HeroUnit>
      <Main>
        <Row>
          <Col xs={12}>
            {props.page.content.rendered && (
              <Content
                dangerouslySetInnerHTML={{
                  __html: props.page.content.rendered
                }}
              />
            )}
            {props.filterSeries && (
              <Installation>
                <div className='text--center'>
                  <h2>Filter Installations</h2>
                  <h3>Select a Model</h3>
                  <h4>View product summary</h4>
                </div>
                <Accordion>
                  {props.filterSeries.map((node, i) => (
                    <div key={node.id}>
                      <AccordionTitle accordionIndex={i}>
                        {node.title.rendered}
                      </AccordionTitle>
                      <AccordionContent accordionIndex={i}>
                        <ModelInstallationFiles
                          slipStream={node.acf.slip_stream_files || true}
                          sweeperPiping={node.acf.sweeper_piping_files || true}
                        />
                      </AccordionContent>
                    </div>
                  ))}
                </Accordion>
              </Installation>
            )}
            {props.separatorSeries && (
              <Installation>
                <div className='text--center'>
                  <h2>Separator Installations</h2>
                  <h3>Select a Model</h3>
                  <h4>View product summary</h4>
                </div>
                <Accordion>
                  {props.separatorSeries.map((node, i) => (
                    <div key={node.id}>
                      <AccordionTitle accordionIndex={i}>
                        {node.title.rendered}
                      </AccordionTitle>
                      <AccordionContent accordionIndex={i}>
                        <ModelInstallationFiles
                          sweeperPiping={node.acf.sweeper_piping_files || true}
                          fullFlow={node.acf.full_flow_files || true}
                          sideStream={node.acf.side_stream_files || true}
                        />
                      </AccordionContent>
                    </div>
                  ))}
                </Accordion>
              </Installation>
            )}
          </Col>
        </Row>
      </Main>
    </Layout>
  )
}

const Main = styled(Container)`
  padding: 45px 15px;
`

const Content = styled.div`
  margin: 0 auto;
  max-width: 960px;
  padding: 1.45rem 1.0875rem;
`

const Installation = styled.div`
  &:first-of-type {
    margin-bottom: 45px;
  }

  .text--center {
    text-align: center;
  }

  h2 {
    text-transform: uppercase;
  }

  h4 {
    color: #ccc;
  }
`
