import Head from 'next/head'
import { HeroContent, HeroUnit } from '../components/hero-unit'
import Layout from '../components/layout'
import styled from 'styled-components'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { PageProps } from '../pages/[slug]'
import Accordion, {
  AccordionContent,
  AccordionTitle
} from '../components/accordion'

export interface TypicalInstallationsPageProps extends PageProps {}

export default function TypicalInstallationsPage(
  props: TypicalInstallationsPageProps
) {
  return (
    <Layout {...props}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroUnit imgSrc={props.heroImg.media_details.sizes.full.source_url}>
        <HeroContent
          content={props.page.acf.content}
          buttons={props.page.acf.buttons}
        />
      </HeroUnit>
      <Main>
        <Row>
          <Col xs={12}>
            {props.page.content.rendered && (
              <Content
                dangerouslySetInnerHTML={{
                  __html: props.page.content.rendered
                }}
              />
            )}
            {/* {props.filterInstalls && (
            <Installation>
              <div className='text--center'>
                <h2>Filter Installations</h2>
                <h3>Select a Model</h3>
                <h4>View product summary</h4>
              </div>
              <Accordion>
                {props.filterInstalls.map(({ node }, i) => (
                  <div key={node.id}>
                    <AccordionTitle accordionIndex={i}>
                      {node.title}
                    </AccordionTitle>
                    <AccordionContent accordionIndex={i}>
                      <ModelInstallationFiles
                        slipStream={node.acf.slip_stream_files || true}
                        sweeperPiping={node.acf.sweeper_piping_files || true}
                      />
                    </AccordionContent>
                  </div>
                ))}
              </Accordion>
            </Installation>
          )} */}
            {/* {props.sepInstalls && (
            <Installation>
              <div className='text--center'>
                <h2>Separator Installations</h2>
                <h3>Select a Model</h3>
                <h4>View product summary</h4>
              </div>
              <Accordion>
                {props.sepInstalls.map(({ node }, i) => (
                  <div key={node.id}>
                    <AccordionTitle accordionIndex={i}>
                      {node.title}
                    </AccordionTitle>
                    <AccordionContent accordionIndex={i}>
                      <ModelInstallationFiles
                        sweeperPiping={node.acf.sweeper_piping_files || true}
                        fullFlow={node.acf.full_flow_files || true}
                        sideStream={node.acf.side_stream_files || true}
                      />
                    </AccordionContent>
                  </div>
                ))}
              </Accordion>
            </Installation>
          )} */}
          </Col>
        </Row>
      </Main>
    </Layout>
  )
}

const Main = styled(Container)`
  padding: 45px 15px;
`

const Content = styled.div`
  margin: 0 auto;
  max-width: 960px;
  padding: 1.45rem 1.0875rem;
`

const Installation = styled.div`
  &:first-of-type {
    margin-bottom: 45px;
  }

  .text--center {
    text-align: center;
  }

  h2 {
    text-transform: uppercase;
  }

  h4 {
    color: #ccc;
  }
`
